name: jup_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - numpy
  - keras
  - scipy
  - imageio
  - scikit-learn
  - scikit-image
  - matplotlib
  - pandas
  - seaborn
  - jupyterlab


